[package]
name = "wasm-test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
serde-wasm-bindgen = "0.4"
wasm-bindgen = { version= "0.2.63", features = ["serde-serialize"] }

